Bài 3.1

In [600]:
import numpy as np
print("Phiên bản Numpy hiện tại",np.__version__)
print("\nCấu hình xây dựng của NumPy:")
np.show_config()

Phiên bản Numpy hiện tại 1.24.3

Cấu hình xây dựng của NumPy:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
  

Bài 3.2

In [601]:
import numpy as np

arr = np.arange(10)
print(f"Mảng arr: {arr}")
print(f"Kiểu dữ liệu của arr: {arr.dtype}")
print(f"Kích thước của arr: {arr.shape}")


Mảng arr: [0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu của arr: int32
Kích thước của arr: (10,)


In [602]:
arr_odd = arr[arr % 2 != 0]
arr_even = arr[arr % 2 == 0]
print(f"Mảng arr_odd : {arr_odd}")
print(f"Mảng arr_even : {arr_even}")


Mảng arr_odd : [1 3 5 7 9]
Mảng arr_even : [0 2 4 6 8]


In [603]:
# Giữ nguyên phần tử chẵn, thay phần tử lẻ bằng 100
arr_update_1 = np.where(arr % 2 != 0, 100, arr)
print(f"Mảng arr_update_1: {arr_update_1}")


Mảng arr_update_1: [  0 100   2 100   4 100   6 100   8 100]


Bài 3.3

In [604]:
arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

arr_c = np.intersect1d(arr_a, arr_b)
print(f"Mảng arr_c (phần tử chung): {arr_c}")


Mảng arr_c (phần tử chung): [2 4]


In [605]:
arr_d = np.setdiff1d(arr_a, arr_b)
print(f"Mảng arr_d (phần tử chỉ có trong arr_a): {arr_d}")


Mảng arr_d (phần tử chỉ có trong arr_a): [1 3 5 6]


In [606]:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])

# Lọc các giá trị >= 5 VÀ <= 10
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print(f"Mảng arr_f (giá trị từ 5 đến 10): {arr_f}")


Mảng arr_f (giá trị từ 5 đến 10): [ 6  9 10  8  6]


Bài 3.4

In [607]:
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[5] = 1
print(f"Mảng arr_zeros: {arr_zeros}")


Mảng arr_zeros: [0 0 0 0 0 1 0 0 0 0]


In [608]:
arr_h = np.arange(10, 25)
print(f"Mảng arr_h (đảo ngược): {arr_h[::-1]}")


Mảng arr_h (đảo ngược): [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [609]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
# Lấy các phần tử khác 0
arr_l = arr_k[arr_k != 0]
print(f"Mảng arr_l (phần tử khác 0): {arr_l}")


Mảng arr_l (phần tử khác 0): [1 2 8 2 1 3 5]


In [610]:
arr_l = np.append(arr_l, [10, 20])
print(f"Mảng arr_l sau khi thêm cuối: {arr_l}")


Mảng arr_l sau khi thêm cuối: [ 1  2  8  2  1  3  5 10 20]


In [611]:
arr_l = np.insert(arr_l, 5, 100)
print(f"Mảng arr_l sau khi thêm 100 vào index 5: {arr_l}")


Mảng arr_l sau khi thêm 100 vào index 5: [  1   2   8   2   1 100   3   5  10  20]


In [612]:
arr_l = np.delete(arr_l, [0, 1, 2])
print(f"Mảng arr_l sau khi xóa index 0, 1, 2: {arr_l}")


Mảng arr_l sau khi xóa index 0, 1, 2: [  2   1 100   3   5  10  20]


Bài 3.5

In [613]:
def read_file_to_list(filename):
    data_list = []
    with open(filename, 'r', encoding='utf-8') as f:
        text = f.read()
    parts = [p.strip() for p in text.replace('\n', ',').split(',')]
    for token in parts:
        if token == '':
            continue
        try:
            if '.' in token:
                value = float(token)
            else:
                value = int(token)
            data_list.append(value)
        except ValueError:
            try:
                data_list.append(float(token))
            except ValueError:
                continue
    return data_list


import numpy as np
height = read_file_to_list('heights_1.txt')
weight = read_file_to_list('weights_1.txt')

# Tạo numpy arrays theo yêu cầu
arr_height = np.array(height)
arr_weight = np.array(weight)



In [614]:
arr_height_m = arr_height * 0.0254

In [615]:
arr_weight_kg = arr_weight * 0.453592

In [616]:
arr_bmi = arr_weight_kg / (arr_height_m ** 2)

In [617]:
print(arr_weight_kg[50])

90.7184


In [618]:
arr_height_m_100 = arr_height_m[100:111]

In [619]:
underweight_players = arr_bmi < 21
print(underweight_players)

[False False False ... False False False]


In [620]:
avg_height = np.mean(arr_height_m)
avg_weight = np.mean(arr_weight_kg)

print("Chiều cao trung bình: ", avg_height)
print("Cân nặng trung bình: ", avg_weight)

Chiều cao trung bình:  1.8717094674556212
Cân nặng trung bình:  91.33974052071005


In [621]:
max_height = np.max(arr_height_m)
max_weight = np.max(arr_weight_kg)

print("Chiều cao lớn nhất: ", max_height)
print("Cân nặng lớn nhất: ", max_weight)

Chiều cao lớn nhất:  2.1082
Cân nặng lớn nhất:  131.54167999999999


In [622]:
min_height = np.min(arr_height_m)
min_weight = np.min(arr_weight_kg)

print("Chiều cao nhỏ nhất: ", min_height)
print("Cân nặng nhỏ nhất: ", min_weight)

Chiều cao nhỏ nhất:  1.7018
Cân nặng nhỏ nhất:  68.0388


Bài 3.6

In [623]:
import numpy as np

# Câu 1
arr = np.full((3, 3), True)
print("Câu 1:\n", arr)

Câu 1:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [624]:
# Câu 2
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("Câu 2:\n", arr_2D)

Câu 2:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [625]:
# Câu 3
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("Câu 3:\n", arr_2D)

Câu 3:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [626]:
# Câu 4
arr_2D = np.flip(arr_2D, axis=0)
print("Câu 4:\n", arr_2D)

Câu 4:
 [[8 7 6]
 [2 1 0]
 [5 4 3]]


In [627]:
# Câu 5
arr_2D = np.flip(arr_2D, axis=1)
print("Câu 5:\n", arr_2D)

Câu 5:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]


In [628]:
# Câu 6
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
print("Câu 6:\n", np.isnan(arr_2D_null))

Câu 6:
 [[False False False]
 [ True False False]
 [False  True False]
 [False False False]]


Bài 3.7

In [629]:
import numpy as np
import ast

# Doc du lieu tu tap tin baseball_2D.txt
with open('baseball_2D.txt', 'r', encoding='utf-8-sig') as f:
    data_text = f.read()

# Parse du lieu tu dinh dang list
baseball = ast.literal_eval(data_text)


In [630]:
# Tạo 2D numpy array np_baseball
np_baseball = np.array(baseball)
print("Kiểu dữ liệu của np_baseball:", np_baseball.dtype)
print("Kích thước của np_baseball:", np_baseball.shape)

Kiểu dữ liệu của np_baseball: int32
Kích thước của np_baseball: (1015, 2)


In [631]:
# In các giá trị của dòng thứ 50
print("\nDòng thứ 50 (index 49) của np_baseball:")
print(np_baseball[49])


Dòng thứ 50 (index 49) của np_baseball:
[ 70 195]


In [632]:
#Tạo numpy array np_weight với cột 2
np_weight = np_baseball[:, 1]
print("\nnp_weight (cân nặng) - 10 giá trị đầu tiên:")
print(np_weight[:10])
print(f"Kiểu dữ liệu của np_weight: {np_weight.dtype}")


np_weight (cân nặng) - 10 giá trị đầu tiên:
[180 215 210 210 188 176 209 200 231 180]
Kiểu dữ liệu của np_weight: int32


In [633]:
# Chiều cao của vận động viên thứ 124
np_height = np_baseball[:, 0]
height_124 = np_height[123]  # Index 123 vì đếm từ 0
print(f"\nChiều cao của vận động viên thứ 124: {height_124} inches")


Chiều cao của vận động viên thứ 124: 75 inches


In [634]:
# Chiều cao trung bình, cân nặng trung bình
avg_height_baseball = np.mean(np_height)
avg_weight_baseball = np.mean(np_weight)

print(f"\nChiều cao trung bình: {avg_height_baseball:.2f} inches")
print(f"Cân nặng trung bình: {avg_weight_baseball:.2f} pounds")


Chiều cao trung bình: 73.69 inches
Cân nặng trung bình: 201.35 pounds


In [635]:

# Tính hệ số tương quan Pearson
correlation = np.corrcoef(np_height, np_weight)[0, 1]

print(f"\nHệ số tương quan giữa chiều cao và cân nặng: {correlation:.4f}")

# Phân tích
if correlation > 0.7:
    print("Nhận xét: Có tương quan thuận MẠNH giữa chiều cao và cân nặng.")
    print("Càng cao thì cân nặng có xu hướng càng nặng.")
elif correlation > 0.3:
    print("Nhận xét: Có tương quan thuận trung bình giữa chiều cao và cân nặng.")
    print("Những cầu thủ cao hơn có xu hướng nặng hơn.")
elif correlation > 0:
    print("Nhận xét: Có tương quan thuận yếu giữa chiều cao và cân nặng.")
elif correlation > -0.3:
    print("Nhận xét: Có tương quan nghịch yếu giữa chiều cao và cân nặng.")
else:
    print("Nhận xét: Có tương quan nghịch giữa chiều cao và cân nặng.")


Hệ số tương quan giữa chiều cao và cân nặng: 0.5315
Nhận xét: Có tương quan thuận trung bình giữa chiều cao và cân nặng.
Những cầu thủ cao hơn có xu hướng nặng hơn.


Bài 3.8

In [636]:
import numpy as np

# Đọc positions.txt (thường không có BOM ở đầu, nhưng vẫn làm sạch)
with open('positions.txt', 'r', encoding='utf-8-sig') as f:
    positions = [pos.strip() for pos in f.read().strip().split(',') if pos.strip()]

# Đọc heights.txt — quan trọng: dùng encoding='utf-8-sig' để tự động bỏ BOM
with open('heights.txt', 'r', encoding='utf-8-sig') as f:
    raw_text = f.read().strip()
    height_strings = [h.strip() for h in raw_text.split(',') if h.strip()]
    heights = [int(h) for h in height_strings]  # giờ sẽ không còn '191'

# Kiểm tra độ dài (phải bằng nhau)
print(f"Số cầu thủ: {len(positions)}")
print(f"Số chiều cao: {len(heights)}")
assert len(positions) == len(heights), "Lỗi: 2 file có số lượng dữ liệu khác nhau!"

# ==================================================================
# 1a) Tạo np_positions
# ==================================================================
np_positions = np.array(positions)
print("\n1a) np_positions dtype:", np_positions.dtype)

# ==================================================================
# 1b) Tạo np_heights
# ==================================================================
np_heights = np.array(heights, dtype=float)  # dùng float để sau tính mean chính xác hơn
print("1b) np_heights dtype:", np_heights.dtype)

# ==================================================================
# 2) Chiều cao trung bình của GK
# ==================================================================
gk_heights = np_heights[np_positions == 'GK']
avg_gk = gk_heights.mean()
print(f"\n2) Chiều cao trung bình thủ môn (GK): {avg_gk:.2f} cm (n = {len(gk_heights)})")

# ==================================================================
# 3) Chiều cao trung bình các vị trí khác
# ==================================================================
other_heights = np_heights[np_positions != 'GK']
avg_other = other_heights.mean()
print(f"3) Chiều cao trung bình các vị trí khác: {avg_other:.2f} cm (n = {len(other_heights)})")

# ==================================================================
# 4) Tạo structured array players
# ==================================================================
dt = np.dtype([
    ('position', 'U5'),
    ('height', float)
])
players = np.array(list(zip(positions, heights)), dtype=dt)
print("\n4) Structured array 'players' đã tạo thành công!")

# ==================================================================
# 5) Sắp xếp và tìm cầu thủ cao nhất/thấp nhất
# ==================================================================
players_sorted = np.sort(players, order='height')

lowest = players_sorted[0]
highest = players_sorted[-1]

print(f"\n5) Kết quả sau khi sắp xếp theo chiều cao:")
print(f"   → Thấp nhất: {lowest['position']} - {lowest['height']:.0f} cm")
print(f"   → Cao nhất : {highest['position']} - {highest['height']:.0f} cm")

# Bonus: Top 5 cao nhất & thấp nhất
print("\n   Top 5 cầu thủ cao nhất:")
for p in players_sorted[-5:][::-1]:
    print(f"   • {p['position']:2} : {p['height']:.0f} cm")

print("   Top 5 cầu thủ thấp nhất:")
for p in players_sorted[:5]:
    print(f"   • {p['position']:2} : {p['height']:.0f} cm")

Số cầu thủ: 8847
Số chiều cao: 8847

1a) np_positions dtype: <U2
1b) np_heights dtype: float64

2) Chiều cao trung bình thủ môn (GK): 188.23 cm (n = 930)
3) Chiều cao trung bình các vị trí khác: 180.99 cm (n = 7917)

4) Structured array 'players' đã tạo thành công!

5) Kết quả sau khi sắp xếp theo chiều cao:
   → Thấp nhất: M - 158 cm
   → Cao nhất : GK - 208 cm

   Top 5 cầu thủ cao nhất:
   • GK : 208 cm
   • GK : 203 cm
   • A  : 203 cm
   • GK : 202 cm
   • GK : 202 cm
   Top 5 cầu thủ thấp nhất:
   • M  : 158 cm
   • A  : 160 cm
   • M  : 160 cm
   • M  : 160 cm
   • M  : 160 cm


Bài 3.9

In [637]:
import pandas as pd

euro12 = pd.read_csv('euro2012.csv')

print("Kiểu dữ liệu của euro12:", type(euro12))
print("Kích thước của euro12:", euro12.shape)
print("Danh sách các cột của euro12:", euro12.columns)


Kiểu dữ liệu của euro12: <class 'pandas.core.frame.DataFrame'>
Kích thước của euro12: (16, 36)
Danh sách các cột của euro12: Index(['Unnamed: 0', 'Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')


In [638]:
print("Giá trị cột Goals:\n", euro12['Goals'])

Giá trị cột Goals:
 0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64


In [639]:
num_teams = euro12['Team'].nunique()
print("Số đội tham gia Euro2012:", num_teams)


Số đội tham gia Euro2012: 16


In [640]:
print("Thông tin của Euro2012:\n", euro12.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Unnamed: 0                  16 non-null     int64  
 1   Team                        16 non-null     object 
 2   Goals                       16 non-null     int64  
 3   Shots on target             16 non-null     int64  
 4   Shots off target            16 non-null     int64  
 5   Shooting Accuracy           16 non-null     object 
 6   % Goals-to-shots            16 non-null     object 
 7   Total shots (inc. Blocked)  16 non-null     int64  
 8   Hit Woodwork                16 non-null     int64  
 9   Penalty goals               16 non-null     int64  
 10  Penalties not scored        16 non-null     int64  
 11  Headed goals                16 non-null     int64  
 12  Passes                      16 non-null     int64  
 13  Passes completed            16 non-nu

In [641]:
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
print(discipline)

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0


In [642]:
discipline_sorted = discipline.sort_values(by=['Red Cards', 'Yellow Cards'], ascending=False)
print(discipline_sorted)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0


In [643]:
mean_yellow_cards = euro12['Yellow Cards'].mean()
print(mean_yellow_cards)

7.4375


In [644]:
teams_more_than_6_goals = euro12[euro12['Goals'] > 6]
print(teams_more_than_6_goals)

    Unnamed: 0     Team  Goals  Shots on target  Shots off target  \
5            5  Germany     10               32                32   
13          13    Spain     12               42                33   

   Shooting Accuracy % Goals-to-shots  Total shots (inc. Blocked)  \
5             47.80%           15.60%                          80   
13            55.90%           16.00%                         100   

    Hit Woodwork  Penalty goals  ...  Saves made  Saves-to-shots ratio  \
5              2              1  ...          10                62.60%   
13             0              1  ...          15                93.80%   

    Fouls Won  Fouls Conceded Offsides  Yellow Cards  Red Cards  Subs on  \
5          63              49       12             4          0       15   
13        102              83       19            11          0       17   

    Subs off  Players Used  
5         15            17  
13        17            18  

[2 rows x 36 columns]


In [645]:
teams_starting_with_g = euro12[euro12['Team'].str.startswith('G')]
print(teams_starting_with_g)

   Unnamed: 0     Team  Goals  Shots on target  Shots off target  \
5           5  Germany     10               32                32   
6           6   Greece      5                8                18   

  Shooting Accuracy % Goals-to-shots  Total shots (inc. Blocked)  \
5            47.80%           15.60%                          80   
6            30.70%           19.20%                          32   

   Hit Woodwork  Penalty goals  ...  Saves made  Saves-to-shots ratio  \
5             2              1  ...          10                62.60%   
6             1              1  ...          13                65.10%   

   Fouls Won  Fouls Conceded Offsides  Yellow Cards  Red Cards  Subs on  \
5         63              49       12             4          0       15   
6         67              48       12             9          1       12   

   Subs off  Players Used  
5        15            17  
6        12            20  

[2 rows x 36 columns]


In [646]:
print("7 cột đầu của euro12:\n", euro12.iloc[:, :7])

7 cột đầu của euro12:
     Unnamed: 0                 Team  Goals  Shots on target  Shots off target  \
0            0              Croatia      4               13                12   
1            1       Czech Republic      4               13                18   
2            2              Denmark      4               10                10   
3            3              England      5               11                18   
4            4               France      3               22                24   
5            5              Germany     10               32                32   
6            6               Greece      5                8                18   
7            7                Italy      6               34                45   
8            8          Netherlands      2               12                36   
9            9               Poland      2               15                23   
10          10             Portugal      6               22                42   
11   

In [647]:
print("Tất cả các cột, trừ 3 cột cuối:\n", euro12.iloc[:, :-3])

Tất cả các cột, trừ 3 cột cuối:
     Unnamed: 0                 Team  Goals  Shots on target  Shots off target  \
0            0              Croatia      4               13                12   
1            1       Czech Republic      4               13                18   
2            2              Denmark      4               10                10   
3            3              England      5               11                18   
4            4               France      3               22                24   
5            5              Germany     10               32                32   
6            6               Greece      5                8                18   
7            7                Italy      6               34                45   
8            8          Netherlands      2               12                36   
9            9               Poland      2               15                23   
10          10             Portugal      6               22                4

In [648]:
print("Các cột: Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards:\n", euro12[['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']])

Các cột: Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards:
                    Team  Goals Shooting Accuracy  Yellow Cards  Red Cards
0               Croatia      4            51.90%             9          0
1        Czech Republic      4            41.90%             7          0
2               Denmark      4            50.00%             4          0
3               England      5            50.00%             5          0
4                France      3            37.90%             6          0
5               Germany     10            47.80%             4          0
6                Greece      5            30.70%             9          1
7                 Italy      6            43.00%            16          0
8           Netherlands      2            25.00%             5          0
9                Poland      2            39.40%             7          1
10             Portugal      6            34.30%            12          0
11  Republic of Ireland      1            36.

In [649]:
specific_columns = euro12.loc[euro12['Team'].isin(['England', 'Italy', 'Russia']), ['Team', 'Shooting Accuracy']]
print("Các cột chỉ hiển thị 'Team','Shooting Accuracy' từ 'England', 'Italy', 'Russia':\n", specific_columns)

Các cột chỉ hiển thị 'Team','Shooting Accuracy' từ 'England', 'Italy', 'Russia':
        Team Shooting Accuracy
3   England            50.00%
7     Italy            43.00%
12   Russia            22.50%


Bài 3.10

In [650]:
import pandas as pd


drink = pd.read_csv('drinks.csv', index_col=0)

print("Kiểu dữ liệu của drink:", type(drink))
print("Kích thước của drink:", drink.shape)
print("Tên các cột của drink:", drink.columns)
print("5 dòng dữ liệu đầu tiên của drink:\n", drink.head())
print("5 dòng dữ liệu cuối cùng của drink:\n", drink.tail())

Kiểu dữ liệu của drink: <class 'pandas.core.frame.DataFrame'>
Kích thước của drink: (193, 6)
Tên các cột của drink: Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')
5 dòng dữ liệu đầu tiên của drink:
        country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF  
5 dòng dữ liệu cuối cùng của drink:
        cou

In [651]:
average_beer = drink.groupby('continent')['beer_servings'].mean()
print("Số lượng bia tiêu thụ trung bình ở mỗi châu lục:\n", average_beer)

Số lượng bia tiêu thụ trung bình ở mỗi châu lục:
 continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64


In [652]:
wine_stats = drink.groupby('continent')['wine_servings'].describe()
print("Thông tin thống kê tổng quát về số lượng rượu vang được tiêu thụ ở mỗi châu lục:\n", wine_stats)

Thông tin thống kê tổng quát về số lượng rượu vang được tiêu thụ ở mỗi châu lục:
            count        mean        std  min   25%    50%     75%    max
continent                                                               
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0


In [653]:
mean_beer_wine = drink.groupby('continent')[['beer_servings', 'wine_servings']].mean()
print("Số lượng các loại bia và rượu tiêu thụ trung bình ở mỗi châu lục:\n", mean_beer_wine)

Số lượng các loại bia và rượu tiêu thụ trung bình ở mỗi châu lục:
            beer_servings  wine_servings
continent                              
AF             61.471698      16.264151
AS             37.045455       9.068182
EU            193.777778     142.222222
OC             89.687500      35.625000
SA            175.083333      62.416667


In [654]:
median_beer_wine = drink.groupby('continent')[['beer_servings', 'wine_servings']].median()
print("Giá trị trung vị cho các loại bia và rượu tiêu thụ ở mỗi châu lục:\n", median_beer_wine)

Giá trị trung vị cho các loại bia và rượu tiêu thụ ở mỗi châu lục:
            beer_servings  wine_servings
continent                              
AF                  32.0            2.0
AS                  17.5            1.0
EU                 219.0          128.0
OC                  52.5            8.5
SA                 162.5           12.0


In [655]:
spirit_stats = drink.groupby('continent')['spirit_servings'].aggregate(['mean', 'max', 'min'])
print("Số lượng rượu mạnh tiêu thụ trung bình, lớn nhất và nhỏ nhất ở mỗi châu lục:\n", spirit_stats)

Số lượng rượu mạnh tiêu thụ trung bình, lớn nhất và nhỏ nhất ở mỗi châu lục:
                  mean  max  min
continent                      
AF          16.339623  152    0
AS          60.840909  326    0
EU         132.555556  373    0
OC          58.437500  254    0
SA         114.750000  302   25


In [656]:
sorted_beer = drink.sort_values(by='beer_servings', ascending=False)
top_5_beer_consumers = sorted_beer.head(5)
bottom_5_beer_consumers = sorted_beer.tail(5)
print("5 quốc gia có lượng tiêu thụ bia nhiều nhất:\n", top_5_beer_consumers[['beer_servings']])
print("5 quốc gia có lượng tiêu thụ bia ít nhất:\n", bottom_5_beer_consumers[['beer_servings']])

5 quốc gia có lượng tiêu thụ bia nhiều nhất:
      beer_servings
117            376
45             361
62             347
65             346
98             343
5 quốc gia có lượng tiêu thụ bia ít nhất:
      beer_servings
107              0
158              0
111              0
128              0
0                0
